"""Removido relação NN de produtos e descontos

Revision ID: 2c4bd67570eb
Revises: 7b4459bb5ea2
Create Date: 2025-02-06 16:48:20.294440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c4bd67570eb'
down_revision: Union[str, None] = '7b4459bb5ea2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_discounts_id', table_name='product_discounts')
    op.drop_table('product_discounts')
    op.add_column('discounts', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'discounts', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'discounts', type_='foreignkey')
    op.drop_column('discounts', 'product_id')
    op.create_table('product_discounts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('discount_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['discount_id'], ['discounts.id'], name='product_discounts_discount_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='product_discounts_product_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='product_discounts_pkey')
    )
    op.create_index('ix_product_discounts_id', 'product_discounts', ['id'], unique=False)
    # ### end Alembic commands ###
