"""add admin id to order

Revision ID: 3391632d165b
Revises: fb95444f2182
Create Date: 2025-04-28 17:36:51.308734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3391632d165b'
down_revision: Union[str, None] = 'fb95444f2182'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('admin_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'admin_id')
    # ### end Alembic commands ###
