"""adicionado imagens para categorias

Revision ID: 3939bfd86f61
Revises: da2da1b5b621
Create Date: 2025-03-27 17:09:31.000415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3939bfd86f61'
down_revision: Union[str, None] = 'da2da1b5b621'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('image_path', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'image_path')
    # ### end Alembic commands ###
