"""Imagens de perfil

Revision ID: 8a8b3a79767e
Revises: 3939bfd86f61
Create Date: 2025-04-01 18:04:12.983572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a8b3a79767e'
down_revision: Union[str, None] = '3939bfd86f61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image_path', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'image_path')
    # ### end Alembic commands ###
