"""adicionado campo de imagem aos produtos

Revision ID: 93f2dc1a3c6e
Revises: 58188720582c
Create Date: 2025-03-21 17:50:46.904266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93f2dc1a3c6e'
down_revision: Union[str, None] = '58188720582c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_path', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'image_path')
    # ### end Alembic commands ###
